name: prensa-css-engine CD/QA
"on":
  push:
    branches:
      - qa

jobs:
  release:
    name: prensa-css-engine deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - run: npm install
      - run: npm run cd
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          